version: '3.9'
services:
  gateway:
    build: 
      context: . 
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:80"
  bookservice:
    build: 
      context: . 
      dockerfile: ./bookservice/Dockerfile
    ports: 
      - "8000:8083"
