version: '3.9'
services:
  gateway:
    build: 
      context: ./krakend/
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
  bookservice:
    build: 
      context: ./bookservice/ 
      dockerfile: ./Dockerfile
    ports: 
      - "8000:8083"
